### PR TITLE
The same notebooks but in Plots.jl

### PR DESCRIPTION
**Pull request by yuxi-liu-wired**
Rewrote the plotting code in the language of Plots.jl instead of PyPlot.

### CODE REVIEW

**Comment by Datseris** [comment]
Hi @yuxiliu1995 , please replace the original files with PyPlot with these ones with Plots.jl. I don't want to keep both, this just makes it harder to maintain... Thank you!

**Comment by yuxi-liu-wired** [comment]
Okay. I replaced the notebooks, also updated the version number to Julia 1.3.0

**Comment by Datseris** [comment]
I don't see any plots in the second notebook: https://github.com/yuxiliu1995/JuliaDynamics/blob/tutorial-gr-version/tutorials/Youtube_JuliaLang_tutorial/2.%20ChaosTools.ipynb

**Comment by yuxi-liu-wired** [comment]
I just generated all the plots, and also amended notebook 2 to be clearer. In the original notebook, the attractor intersects with the y=0 plane in two separate sets (one set contains the trajectories piercing the plane in the y < 0 to y > 0 direction, the other the opposite). I made the two separate sets of different colors.

**Pull request merged**
